### ISSUE TITLE
Unable to shutdown on T500 artix with s6

### ISSUE THREAD

**Issue by LordRusk** [skarnet/s6#12]
S6 was recently supported by  Artix Linux, so I wanted to try it out. I migrated my machine to use s6, and I was surprised. I noticed a slight speedup from when grub is done to when I can log in compared to runit, what I was using previously. I'm loving s6 so far, the way it works is simple yet powerful, it seems to be a lot more open-ended then runit as well.

 But, onto the problem. On my T500, my current main machine, whenever I run `sudo shutdown -h 0` it shuts down Xorg, kills the processes, then it just stays on `system restart: system halted` and won't actually shutdown. Restarting works, however. On runit and s6 it takes a few seconds to actually restart, but I've left it on `system restart: system halted` for at least 30 seconds and it stayed running, I ended up having to just hold the power button, what I have been doing. I searched around, tried a few different commands to shutdown that ended in the same problem. I thought it might have been something with the migration, so I decided to reinstall Artix and got the same problem. I'm not sure if I needed to post this to the artix forums or here, so I went with here. Any response would be greatly appreciated.

**Comment by Obarun** [comment]
you ask for an halt not for a shutdown/poweroff. According to the documentation:

> -h : at the end of the shutdown sequence, halt the system. The behaviour of this option may be altered with -H or -P. 

So, instead of using -h use sudo shutdown -p now

**Comment by LordRusk** [comment]
Yup, that fixed it. It's the little things that get me i swear. Thanks for the help!
