### ISSUE TITLE
Unable to build after #82e33dd

### ISSUE THREAD

**Issue by raymondtri** [skarnet/s6#14]
Following the standard build-from-code process

```
RUN cd /tmp && git clone git://git.skarnet.org/skalibs && cd skalibs && ./configure && make && make install
RUN cd /tmp && git clone git://git.skarnet.org/execline && cd execline && ./configure && make && make install
RUN cd /tmp && git clone git://git.skarnet.org/s6 && cd s6 && ./configure && make && make install
```

However, now we get build failures stating that `recipe for target 's6-ftrig-listen' failed` because `cannot find -lexecline`

This seems to be directly correlated to the recent [#82e33dd](https://github.com/skarnet/s6/commit/82e33dd5f3420f7b58ef2cd7feefd8b3c74b9b10)

Any thoughts? Or have build instructions changed?

Thanks,
Ray

**Comment by skarnet** [comment]
It was a bug indeed, which is fixed in the current git head. Please try again and see if it works for you now?
