### ISSUE TITLE
compiling s6 using tcc failed

### ISSUE THREAD

**Issue by hoomanist** [skarnet/s6#16]
when i tried to compile s6 using tcc i get this error massage:
`exec tcc -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -iquote src/include-local -Isrc/include -fPIC -Werror=implicit-function-declaration -Werror=implicit-int -Werror=pointer-sign -Werror=pointer-arith  -pipe -Wall -std=c99 -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -Wa,--noexecstack -ffunction-sections -fdata-sections -O2 -fomit-frame-pointer -fno-stack-protector  -c -o src/daemontools-extras/s6-log.o src/daemontools-extras/s6-log.c
tcc: error: invalid option -- '-iquote'
`

the command was:
make CC=tcc install

**Comment by skarnet** [comment]
That would be a bug-report to send to the tcc team ;-)

**Comment by skarnet** [comment]
Closing this, since `-iquote` is an important feature of a C compiler and there's nothing I can do for compilers that don't support it.

**Comment by hoomanist** [comment]
ok thanks
