### ISSUE TITLE
ExecStartPost equivalent functionality in s6

### ISSUE THREAD

**Issue by tdeva14** [skarnet/s6#19]
Recently I have been migrating services from systemd to s6. Few of my systemd services use ExecStartPost commands after ExecStart is run but I couldn't see any equivalent functionality in s6. Basically I want to run few commands as soon as my main process is started (it could be a daemon or a oneshot process). Is there a way to do this?

I was actually thinking to start a script prior to starting the main process and use s6-svwait until the service is up/ready and run the commands but I later realised that is going to work only for longrun processes and not for oneshot (since supervise doesn't run for oneshot). Any help is much appreciated.

**Comment by skarnet** [comment]
Your idea with a separate script and `s6-svwait` is the correct one, and if you're sticking with pure s6 it's the simplest way of doing it.

But bear in mind that s6 is a _process supervision suite_, so indeed it only manages longruns. If you need to mix-and-match longruns with oneshots, e.g. you want to convert a full systemd service set to s6, then [s6-rc](https://skarnet.org/software/s6-rc/) is the piece of software you need: it's a full service manager. With s6-rc, an ExecStartPost line would simply be implemented as a oneshot that depends on the service you want to run it after.

**Comment by tdeva14** [comment]
Thanks for the prompt response. I would probably go with invoking a script that will do the trick for me
