### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by subnut** [skarnet/s6#22]
I have read your whole Blog on s6, and I have a few questions -
- Benefits over runit?
- why use database instead of symlinks?
- why some command-line options do not have a long form?
- you said that the concept of runlevels in runit didn't work in case of udevd, which had to be run unsupervised in runlevel 1. How does s6 address this problem?
- why there is no `man` documentation for s6 and it's related binaries?
- did Gerrit Pape abandon runit? Has development stopped?

**Comment by skarnet** [comment]
Hi @subnut,
I have answered your questions on the supervision mailing-list. You can read my answer here (with my apologies for the horrendous formatting of mail-archive.com):
[https://www.mail-archive.com/supervision@list.skarnet.org/msg02692.html](https://www.mail-archive.com/supervision@list.skarnet.org/msg02692.html)

**Comment by subnut** [comment]
Thanks for the detailed reply! I really appreciate the way you write answers!
