### ISSUE TITLE
Failed to build the latest s6 v2.10.0.0

### ISSUE THREAD

**Issue by JSONY18** [skarnet/s6#25]
I just followed the standard build and install process for the latest s6 version. 
The following error broke the installing process, see details below, could you give me some guide how to get  solve this isseu.

`src/libs6/s6_svc_ok.c: In function 's6_svc_ok':
src/libs6/s6_svc_ok.c:21:3: error: implicit declaration of function 'fd_islocked' [-Werror=implicit-function-declaration]
   r = fd_islocked(fd) ;
   ^
cc1: some warnings being treated as errors
make: *** [Makefile:135: src/libs6/s6_svc_ok.lo] Error 1`

**Comment by skarnet** [comment]
You already opened an issue on this subject, which I closed after giving you the answer.
Again: make sure you are linking against skalibs-2.10.0.0 or skalibs-2.10.0.1. The latest version of s6 will not build against an earlier version of skalibs.

Please stop repeatedly opening issues about this.
