### ISSUE TITLE
[feature]  Provide already-built (perhaps statically linked) binaries

### ISSUE THREAD

**Issue by cipriancraciun** [skarnet/s6#27]
Unfortunately many Linux distributions (for example OpenSUSE) don't provide any `s6` (or `execline`) builds.  Moreover building `s6` is not straight forward as it depends on `skalibs` (with the same fate).

Therefore it would be nice if you could provide an already-built set of binaries (perhaps statically linked) at least for x86_64.

Alternatively in order to improve compatibility with as many Linux distributions, you could:
* start an older CentOS VM (or Debian, Ubuntu, etc.);
* use the `rpath` feature to link the `skalibs` `.so` as relative to where the binaries live;  (say you provide a `bin` and `lib` folder that should always be kept side-by-side;)
* package the binaries and any required `.so` (except the ones provided by `libc`);

**Comment by skarnet** [comment]
s6 is packaged in Debian, Fedora, Ubuntu, Arch, Gentoo, Artix, Alpine, Void, and more. It is present in image creation systems such as Buildroot. There are multiple projects that create an s6 infrastructure running in containers, the best-known one being `s6-overlay`.

If users have trouble getting s6 binaries, _they're really not trying very hard_. End of thread.
