### ISSUE TITLE
Noob here, I have a couple of questions.

### ISSUE THREAD

**Issue by q4zr** [skarnet/s6#31]
I have installed and set up s6 yesterday, but I have read through the docs and there are a bunch of things I cannot understand.

Would you mind answering these few?

1. What is a bundle.
2. How can I enable a service, eg. sddm, on boot.
3. How can I disable a service after it has been enabled for boot.

Thanks

**Comment by skarnet** [comment]
Hi! We don't use Github issues for s6 support; please subscribe to the [supervision mailing-list](https://skarnet.org/lists/) and come to the IRC #s6 channel on OFTC. There, the community will be able to answer your questions and point you to the right direction.
